worker_processes 1;
rtmp_auto_push on;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            deny play all;

            drop_idle_publisher 10s;

            on_publish http://stream-controller:8000/on_publish;

            on_done http://stream-controller:8000/on_done;
        }
    }
}

http {
    server {
        listen 80;
        location / {
            return 200 "nginx-rtmp alive\n";
        }
    }
}
